apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: {{ .Values.service.type }}
  selector: { app: fastapi }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
